#!groovy

pipeline {
    agent {
    	label 'swarm'
    }
    stages {
        stage('Build notary-server') {
            steps {
                script {
                    docker.withRegistry('https://repo.rancher.zone', 'nexus') {
                        def image = docker.build("timw/notary-server:latest", "-f Dockerfile.server ." )
                        image.push()
                    }
                }
            }
        }
    }
}