.DEFAULT=build

build:
	docker build -t mars:5000/timw/jenkins .

push:
	docker push mars:5000/timw/jenkins

#start:
#	docker-compose down && docker-compose up -d && docker-compose logs -f

#stop:
#	docker-compose down
